### ISSUE TITLE
prompt user for action on various new entry callsign values

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#479]
- [x] if callsign is blank or 'Team', prompt the user and do not accept
- [x] if callsign 'appears wacky' such as 75623 etc, prompt the user, with 'save the message as it is' vs 'go back and edit the callsign'
- [ ] if callsign does not have an existing tab, and is 'similar to' an existing tab, prompt the user with the same two options

- callsign 75623 (or such) was noticed at the 7/9/22 all-team training.  Most likely due to operator confusion, but, should be detectable.
- nearly-identical callsigns should probably actually be the same callsign; prompting the user before accepting should reduce the team tab count and improve consistency (i.e. 'before-the-fact'); merging content from one team tab into another (i.e. 'after-the-fact') is a different issue

**Comment by RadiosPRN** [comment]
One idea to help reduce minor differences in team names is to have customizable quick text options (team names) that appear on the new radio dialog which allows the operator to click the appropriate team name instead of typing in a team name. This will not cover all scenarios but in our case 10 team names would probably cover over 95% of our searches. This may not be quite so feasible if you have a lot of variation in team names.

**Comment by RadiosPRN** [comment]
I was referring to the change callsign dialog that pops up the first time a radio calls. I don't believe it has any options or dropdowns to select a team name other than manually typing in a name. This is usually where our mistakes are made when someone mistypes the team name which then creates a nearly duplicate tab. It's probably more of a problem because we use the phonetic alphabet instead of numbers which makes mistakes more likely. I understand what you're saying though, this may not be a good option.

**Comment by caver456** [comment]
[sent this by email - not sure why it didn't show here]
Ah - didn't think about it for the change callsign dialog.  At the very least, adding the dropdown of existing team names there would be helpful, in the same manner as the callsign field in the new entry dialog.  There's probably an even better solution, like a toggle / slider button with two choices, the default being 'new team name' and the other choice being 'existing team name'.  Definitely deserves some thought.

**Comment by caver456** [comment]
Ah - didn't think about it for the change callsign dialog.  At the very
least, adding the dropdown of existing team names there would be helpful,
in the same manner as the callsign field in the new entry dialog.  There's
probably an even better solution, like a toggle / slider button with two
choices, the default being 'new team name' and the other choice being
'existing team name'.  Definitely deserves some thought.

**Comment by caver456** [comment]
Picking this back up as part of the 4.0 roadmap.  Re-reading this thread fresh, looks like @RadiosPRN was thinking of callsigns that haven't yet been assigned as well as callsigns that have already been assigned (i.e. a second radio for an existing callsign) - but I was only responding about callsigns that have already been assigned.

The phonetic alphabet typos thing makes sense.  Maybe autocomplete would be a good option that doesn't take up any real estate?  A pre-populated combo box (similar to the callsign field in the NED) does seem like a good idea too.  Or both.  Those two aren't mutually exclusive.  Will think about it some more.

**Comment by caver456** [comment]
Making a separate issue from these last few suggestions, since they are largely a separate-but-related topic, in order to move forward with this issue as described initially.

**Comment by caver456** [comment]
Another thought - just use the first letter as the team name?  Saying 'alpha' on the radio could mean you just use team name 'A' in radiolog.  That's up to the agency of course, but it seems like a quick solution, especially for saving real estate in the team tabs display.

**Comment by caver456** [comment]
The third category, 'nearly-identical' callsigns, is mostly handled in the teamField validation, including case-changes and whitespace differences, so they all appear in the same single team tab rather than spawning a new team tab.  If more cases like this are noticed in the future, this should be reopened, but for now it's already fixed.  The new validation code structure should make any future validation edits easier.
