### ISSUE TITLE
reduce typing and typos for common team names in CCD and NED

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#560]
Example: teams that use phonetic alphabet for team names - alpha, bravo, charlie - etc - there are different versions of the phonetic alphabet.

Ideas that came up in #479:
- pre-populated combo box
- autocomplete
- quick text buttons in CCD

See ideas and discussion in #479.

Also, from #480 (closed 480 as duplicate of this one, even though this is newer, it's more descriptive and has discussion):

The new callsign field starts with 'Team ' - if the user types something like 'Relay' or 'Transport', possibly followed by a number, then remove the leading 'Team ' as the text is typed. Could make the change as soon as 'enough' of the callsign is typed, like 'Rel' or 'Trans'.

Is this the right way to go? Alternative could be to have radio buttons that select the 'callsign type' and determine what the prefix should be if any, or a toggle switch to either add the 'Team ' prefix or not.

**Comment by caver456** [comment]
Another thought - just use the first letter as the team name? Saying 'alpha' on the radio could mean you just use team name 'A' in radiolog. That's up to the agency of course, but it seems like a quick solution, especially for saving real estate in the team tabs display.

**Comment by RadiosPRN** [comment]
What about the ability to edit a team name after entry? Don't know if this is a reasonable possibility but it would reduce the need to put as much emphasis on typos initially because they could be easily corrected after entry. The problem would probably be that often that would be the only entry for the team so it would need to delete the tab and move the entry to the correct tab.

**Comment by caver456** [comment]
[testing to see if this reply by email gets posted on the github issue]

**Comment by caver456** [comment]
True, it would definitely need to remain editable.  This is more of an
autocomplete or an editable combo box, where selecting something from the
autocomplete or combo box merely populates the editable line field.  Right
now, the callsign field in the NED uses an editable combo box to let you
select from existing teams, but it just populated the callsign field rather
than committing and closing.  With autocomplete, probably just typing the
first letter of the phonetic team name, then whatever key selects the
highlighted autocomplete entry, would do the trick.  Is this what you were
thinking of?

Also, if you amend a message, the callsign is editable.  This does move the
entry to the correct (post-amend) tab.  A new release should be coming
today or tomorrow morning which includes #478.

Hoping to get #560 today as well - but currently working on #505 which may
take some time.

**Comment by RadiosPRN** [comment]
Disregard my message. I thought only the message was editable on amend and did not realize you could also edit the callsign so that takes care of what I was asking about. RadioLog is really looking good with all the improvements!!

**Comment by caver456** [comment]
Thanks and no problem.  I thought this one was more recent, but it was done
in #371 in July 2018.

What version are you running?  Only the recent versions show the version
number in the main window banner.  You probably know that installable
executables have only existed for a month or so, and 3.2.0 introduces the
new directory structure, which should save a lot of trouble going forward.
While it's been heavily tested at home, we haven't really done any searches
with 3.2.0 yet so I definitely get it if you want to hold off a bit.  But
if you are game to help test then 3.2.0 would win, and stay tuned for the
next version today or tonight.

**Comment by RadiosPRN** [comment]
I have 3.2 that I was playing with on my personal computer and 3.1 I believe it is that I was testing on the command trailer computer. Yes I am aware of the executables and that is a HUGE improvement. I had been having several problems with fleetsync messaging on the old version (possibly several years old) but since installing the new version several days ago it has been working flawlessly in the testing I have done. Super excited about all the improvements and also about being able to recommend it to others that may not have a tech person to get it installed.

**Comment by caver456** [comment]
closed #480 as duplicate, and incorporated its text to the first comment on this issue
